# Generated by Django 4.0.4 on 2022-05-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.IntegerField()),
                ('hospital', models.CharField(max_length=1)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('TDP', models.IntegerField(blank=True, null=True)),
                ('PAR', models.FloatField(blank=True, null=True)),
                ('CS', models.FloatField(blank=True, null=True)),
                ('ASJ', models.IntegerField(blank=True, null=True)),
                ('ECG', models.IntegerField(blank=True, null=True)),
                ('FCM', models.FloatField(blank=True, null=True)),
                ('AIE', models.IntegerField(blank=True, null=True)),
                ('DST', models.FloatField(blank=True, null=True)),
                ('IST', models.IntegerField(blank=True, null=True)),
                ('NVP', models.IntegerField(blank=True, null=True)),
                ('talassemia', models.IntegerField(blank=True, null=True)),
                ('diagnostico', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
