# Generated by Django 4.0.4 on 2022-05-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paciente',
            table='pacientes_paciente',
        ),
    ]
