# Generated by Django 4.0.4 on 2022-05-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
