# Generated by Django 4.0.4 on 2022-05-04 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0003_alter_paciente_aie_alter_paciente_asj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente_api',
            fields=[
                ('paciente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='frontend.paciente')),
            ],
            bases=('frontend.paciente',),
        ),
    ]
